-- Replace placeholder focus areas with the real work journey (reverse-chronological).
DELETE FROM experiences;
INSERT INTO experiences (period, title, org, description, icon, tags_json, sort) VALUES
('Jul 2025 — Present', 'Senior Software Engineer', 'UAPP · London, UK', 'Building an AI assistant for students and universities — ASP.NET Core Web APIs, Generative-AI / LLM features, Dockerized cloud deployment, authentication, and unit-tested, dependable services.', 'Sparkles', '["ASP.NET Core","Web API","Generative AI","Docker","Cloud"]', 1),
('Sep 2024 — Present', 'Chief Technology Officer', 'IT Solution Tree · Khulna, BD', 'Technical leadership and architecture — technology selection, product direction, deployment and infrastructure planning, and guiding the engineering team on delivery.', 'Boxes', '["Architecture","System Design","Leadership","Cloud"]', 2),
('Jun 2024 — Jul 2025', 'Software Engineer', 'Bluebay IT Limited · Dhaka, BD', 'Built and maintained production software against real business requirements — ASP.NET Core / Web API development, database-backed applications, feature work, debugging, and deployment.', 'Server', '["ASP.NET Core","Web API","SQL","Deployment"]', 3),
('Oct 2024 — Dec 2024', 'Senior .NET Developer', 'Octopi Digital Ltd. · Contract', 'Senior-level .NET backend work — contributing implementation and architecture to an existing project on a short, focused engagement.', 'Code2', '["C#",".NET","Web API"]', 4),
('2021 — 2024', 'Software Engineer — Trainee → Intern → Engineer', 'Dev Skill · Mirpur, Dhaka, BD', 'Where my professional foundation was built. Progressed from C# trainee through engineering intern to Software Engineer over ~3 years — shipping ASP.NET Core apps, Web APIs, database integration, auth, and production maintenance.', 'GraduationCap', '["C#","ASP.NET Core","Web API","OOP","Databases"]', 5),
('Dec 2020 — Apr 2021', 'Trainee', 'Dreamland IT · Dhaka, BD', 'Where it began — my first formal step into professional software/IT work, building the discipline and technical base for a .NET engineering career.', 'Briefcase', '["Foundations","IT","Software"]', 6);
