-- Refresh skill groups: add full-stack breadth (Node.js, Next.js, FastAPI),
-- a Mobile group (Flutter, Dart), and promote LangChain to a core AI skill.
-- .NET stays the primary/core stack; the new entries are intentionally non-core.
DELETE FROM skill_groups;
INSERT INTO skill_groups (category, icon, description, skills_json, sort) VALUES
('Backend & Architecture', 'Server', 'My core stack for APIs, application services, business workflows, and scalable system architecture.', '[{"name":"C#","color":"#68217A","core":true,"logo":"csharp/csharp-original","desc":"Primary backend language for APIs, services, and business logic."},{"name":".NET","color":"#512BD4","core":true,"logo":"dotnetcore/dotnetcore-original","desc":"Framework for scalable APIs, services, and web applications."},{"name":"ASP.NET Core","color":"#512BD4","core":true,"logo":"dotnetcore/dotnetcore-original","desc":"REST APIs, authentication, middleware, and enterprise services."},{"name":"REST API","color":"#02569B","core":true,"desc":"Clean, secure, versioned API contract design."},{"name":"Clean Architecture","color":"#5E687E","core":true,"desc":"Domain, application, and infrastructure layers, cleanly separated."},{"name":"Microservices","color":"#0052CC","core":true,"desc":"Modular, independently deployable service design."},{"name":"Node.js","color":"#339933","logo":"nodejs/nodejs-original","desc":"JavaScript runtime for services and tooling alongside .NET."}]', 1),
('Frontend & Product UI', 'Layout', 'Building clean, responsive product interfaces and consistent design systems.', '[{"name":"TypeScript","color":"#3178C6","core":true,"logo":"typescript/typescript-original","desc":"Type-safe UI and API-client development."},{"name":"JavaScript","color":"#C9A227","logo":"javascript/javascript-original","desc":"Interactive product interfaces and tooling."},{"name":"Angular","color":"#DD0031","logo":"angularjs/angularjs-original","desc":"Component-driven enterprise web applications."},{"name":"HTML5","color":"#E34F26","logo":"html5/html5-original","desc":"Semantic, accessible markup."},{"name":"CSS3","color":"#1572B6","logo":"css3/css3-original","desc":"Responsive, modern styling."},{"name":"Tailwind CSS","color":"#06B6D4","core":true,"logo":"tailwindcss/tailwindcss-original","desc":"Rapid, consistent UI with a design system."},{"name":"Next.js","color":"#0070F3","desc":"React framework for full-stack, server-rendered web apps."}]', 2),
('Data, Cloud & DevOps', 'Database', 'Storing data and shipping reliably with containers, cloud, and automated pipelines.', '[{"name":"SQL Server","color":"#CC2927","core":true,"logo":"microsoftsqlserver/microsoftsqlserver-plain","desc":"Relational data modeling and T-SQL queries."},{"name":"PostgreSQL","color":"#4169E1","core":true,"logo":"postgresql/postgresql-original","desc":"Robust relational storage and querying."},{"name":"MongoDB","color":"#47A248","logo":"mongodb/mongodb-original","desc":"Document storage for flexible schemas."},{"name":"Docker","color":"#2496ED","core":true,"logo":"docker/docker-original","desc":"Containerized, reproducible deployments."},{"name":"AWS","color":"#FF9900","desc":"Cloud hosting, storage, and services."},{"name":"Azure","color":"#0078D4","logo":"azure/azure-original","desc":"Cloud applications and managed services."},{"name":"GitHub Actions","color":"#2088FF","core":true,"logo":"githubactions/githubactions-original","desc":"CI/CD pipelines and release automation."}]', 3),
('AI & Automation', 'Sparkles', 'Practical LLM features, retrieval-based workflows, and automation that saves real time.', '[{"name":"Python","color":"#3776AB","core":true,"logo":"python/python-original","desc":"Automation scripts and AI tooling."},{"name":"FastAPI","color":"#009688","logo":"fastapi/fastapi-original","desc":"Lightweight Python APIs for AI and automation services."},{"name":"OpenAI","color":"#10A37F","core":true,"desc":"LLM-powered features and assistants."},{"name":"LangChain","color":"#1C7C54","core":true,"desc":"Retrieval and agent-style workflows."},{"name":"Automation","color":"#FF6F00","desc":"Cutting manual work with scripts and AI."}]', 4),
('Mobile', 'Smartphone', 'Cross-platform mobile apps from a single codebase when a project needs to reach phones too.', '[{"name":"Flutter","color":"#02569B","logo":"flutter/flutter-original","desc":"Cross-platform iOS and Android apps from one codebase."},{"name":"Dart","color":"#0175C2","logo":"dart/dart-original","desc":"The language powering Flutter app development."}]', 5);
